### ISSUE TITLE
cant open localhost:3000

### ISSUE THREAD

**Issue by official-louisplayz** [Spiderjockey02/Discord-Bot#239]
cant open localhost:3000

no console error

**Comment by Spiderjockey02** [comment]
What is your OS?

**Comment by official-louisplayz** [comment]
windows 10

**Comment by official-louisplayz** [comment]
and did do the port number to my internet provider
and my windows firewall have all port open

**Comment by Spiderjockey02** [comment]
That's the strange thing, if you are trying to access the API on the same machine no ports would be needed as it's just localhost. umm instead of `localhost:3000` try `internalIP:3000`.
![image](https://user-images.githubusercontent.com/55885015/132506740-bc10aa3c-e1a4-4474-a0cc-c18887067efd.png)
and replace internalIP with the IP it says at `IPv4 Address`

**Comment by official-louisplayz** [comment]
nope does not work

**Comment by TeunHessels** [comment]
do you host them both on you pc

**Comment by TeunHessels** [comment]
otherwise maybe use a open lavalink

**Comment by Spiderjockey02** [comment]
> otherwise maybe use a open lavalink

it's not lavalink, it's the API. Lavalink uses port 5000

**Comment by official-louisplayz** [comment]
yes and my lavalink is open

**Comment by official-louisplayz** [comment]
but i have 2 bots on the pc one with 3000 and one with 3001

**Comment by TeunHessels** [comment]
oh sorry my fault

**Comment by KimYou-Developer** [comment]
let's use port 8080 If port 3000 doesn't work 🤣

**Comment by official-louisplayz** [comment]
eh no that can't

**Comment by official-louisplayz** [comment]
What now
